import { PrismaClient, User } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';
import * as bcrypt from 'bcrypt';
import 'dotenv/config';

const connectionString = process.env.DATABASE_URL;
const pool = new Pool({ connectionString });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('Seeding database...');

  const users: User[] = [];
  for (let i = 1; i <= 10; i++) {
    const hashedPassword = await bcrypt.hash('Password123!', 10);
    const user = await prisma.user.create({
      data: {
        email: `user${i}@example.com`,
        name: `User ${i}`,
        password: hashedPassword,
        role: i === 1 ? 'ADMIN' : 'USER',
      },
    });
    users.push(user);
    console.log(`Created user: ${user.email}`);
  }

  const games = [
    {
      title: 'Cyberpunk 2077',
      genre: 'RPG',
      description: 'An open-world, action-adventure RPG set in Night City.',
      developer: 'CD Projekt Red',
      publisher: 'CD Projekt',
      price: '59.99',
      releaseDate: '2020-12-10',
    },
    {
      title: 'The Witcher 3: Wild Hunt',
      genre: 'RPG',
      description: 'A story-driven open world RPG in a fantasy universe.',
      developer: 'CD Projekt Red',
      publisher: 'CD Projekt',
      price: '39.99',
      releaseDate: '2015-05-19',
    },
    {
      title: 'Red Dead Redemption 2',
      genre: 'Action',
      description: 'An epic tale of honor and loyalty.',
      developer: 'Rockstar Games',
      publisher: 'Rockstar Games',
      price: '59.99',
      releaseDate: '2018-10-26',
    },
    {
      title: 'Grand Theft Auto V',
      genre: 'Action',
      description: 'Experience stories of three criminals in Los Santos.',
      developer: 'Rockstar North',
      publisher: 'Rockstar Games',
      price: '29.99',
      releaseDate: '2013-09-17',
    },
    {
      title: 'Elden Ring',
      genre: 'Action RPG',
      description: 'A dark fantasy action RPG from FromSoftware.',
      developer: 'FromSoftware',
      publisher: 'Bandai Namco',
      price: '59.99',
      releaseDate: '2022-02-25',
    },
    {
      title: 'Dark Souls III',
      genre: 'Action RPG',
      description: 'Embrace the darkness in this challenging action RPG.',
      developer: 'FromSoftware',
      publisher: 'Bandai Namco',
      price: '39.99',
      releaseDate: '2016-04-12',
    },
    {
      title: 'Hogwarts Legacy',
      genre: 'Action RPG',
      description: 'Experience Hogwarts in the 1800s.',
      developer: 'Avalanche Software',
      publisher: 'Warner Bros. Games',
      price: '59.99',
      releaseDate: '2023-02-10',
    },
    {
      title: 'God of War Ragnarok',
      genre: 'Action',
      description: 'Kratos and Atreus venture into the Nine Realms.',
      developer: 'Santa Monica Studio',
      publisher: 'Sony Interactive',
      price: '59.99',
      releaseDate: '2022-11-09',
    },
    {
      title: 'Horizon Zero Dawn',
      genre: 'Action RPG',
      description: 'Unravel mysteries of a world dominated by machines.',
      developer: 'Guerrilla Games',
      publisher: 'Sony Interactive',
      price: '49.99',
      releaseDate: '2017-02-28',
    },
    {
      title: 'Spider-Man Remastered',
      genre: 'Action',
      description: 'Be the Spider-Man in New York City.',
      developer: 'Insomniac Games',
      publisher: 'Sony Interactive',
      price: '49.99',
      releaseDate: '2022-08-12',
    },
    {
      title: 'Baldurs Gate 3',
      genre: 'RPG',
      description: 'Gather your party in the Forgotten Realms.',
      developer: 'Larian Studios',
      publisher: 'Larian Studios',
      price: '59.99',
      releaseDate: '2023-08-03',
    },
    {
      title: 'Starfield',
      genre: 'RPG',
      description: 'Explore the vastness of space.',
      developer: 'Bethesda Game Studios',
      publisher: 'Bethesda Softworks',
      price: '69.99',
      releaseDate: '2023-09-06',
    },
    {
      title: 'Assassins Creed Valhalla',
      genre: 'Action RPG',
      description: 'Become a Viking warrior in Dark Ages England.',
      developer: 'Ubisoft Montreal',
      publisher: 'Ubisoft',
      price: '59.99',
      releaseDate: '2020-11-10',
    },
    {
      title: 'Far Cry 6',
      genre: 'FPS',
      description: 'Fight to liberate a tropical paradise.',
      developer: 'Ubisoft Toronto',
      publisher: 'Ubisoft',
      price: '59.99',
      releaseDate: '2021-10-07',
    },
    {
      title: 'Call of Duty Modern Warfare III',
      genre: 'FPS',
      description: 'The direct sequel to Modern Warfare II.',
      developer: 'Sledgehammer Games',
      publisher: 'Activision',
      price: '69.99',
      releaseDate: '2023-11-10',
    },
    {
      title: 'Battlefield 2042',
      genre: 'FPS',
      description: 'Experience all-out warfare in 128-player battles.',
      developer: 'DICE',
      publisher: 'Electronic Arts',
      price: '59.99',
      releaseDate: '2021-11-19',
    },
    {
      title: 'FIFA 24',
      genre: 'Sports',
      description: 'The worlds game with HyperMotionV technology.',
      developer: 'EA Sports',
      publisher: 'Electronic Arts',
      price: '59.99',
      releaseDate: '2023-09-29',
    },
    {
      title: 'NBA 2K24',
      genre: 'Sports',
      description: 'The most authentic NBA gaming experience.',
      developer: 'Visual Concepts',
      publisher: '2K Sports',
      price: '59.99',
      releaseDate: '2023-09-08',
    },
    {
      title: 'Forza Horizon 5',
      genre: 'Racing',
      description: 'Explore the vibrant landscapes of Mexico.',
      developer: 'Playground Games',
      publisher: 'Xbox Game Studios',
      price: '59.99',
      releaseDate: '2021-11-09',
    },
    {
      title: 'Need for Speed Unbound',
      genre: 'Racing',
      description: 'Race against the odds in Lakeshore City.',
      developer: 'Criterion Games',
      publisher: 'Electronic Arts',
      price: '69.99',
      releaseDate: '2022-12-02',
    },
    {
      title: 'Resident Evil 4 Remake',
      genre: 'Horror',
      description: 'Survival horror reimagined.',
      developer: 'Capcom',
      publisher: 'Capcom',
      price: '59.99',
      releaseDate: '2023-03-24',
    },
    {
      title: 'Dead Space Remake',
      genre: 'Horror',
      description: 'The sci-fi survival horror classic returns.',
      developer: 'Motive Studio',
      publisher: 'Electronic Arts',
      price: '59.99',
      releaseDate: '2023-01-27',
    },
    {
      title: 'Diablo IV',
      genre: 'Action RPG',
      description: 'Endless demons to slaughter and loot to collect.',
      developer: 'Blizzard Entertainment',
      publisher: 'Blizzard Entertainment',
      price: '69.99',
      releaseDate: '2023-06-06',
    },
    {
      title: 'World of Warcraft Dragonflight',
      genre: 'MMORPG',
      description: 'Return to Azeroth and explore the Dragon Isles.',
      developer: 'Blizzard Entertainment',
      publisher: 'Blizzard Entertainment',
      price: '49.99',
      releaseDate: '2022-11-28',
    },
    {
      title: 'Final Fantasy XVI',
      genre: 'RPG',
      description: 'An epic dark fantasy adventure.',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      price: '69.99',
      releaseDate: '2023-06-22',
    },
    {
      title: 'Monster Hunter Rise',
      genre: 'Action RPG',
      description: 'Hunt monsters and craft gear.',
      developer: 'Capcom',
      publisher: 'Capcom',
      price: '59.99',
      releaseDate: '2022-01-12',
    },
    {
      title: 'Hades',
      genre: 'Roguelike',
      description: 'Defy the god of the dead.',
      developer: 'Supergiant Games',
      publisher: 'Supergiant Games',
      price: '24.99',
      releaseDate: '2020-09-17',
    },
    {
      title: 'Hollow Knight',
      genre: 'Metroidvania',
      description: 'Forge your own path in a vast ruined kingdom.',
      developer: 'Team Cherry',
      publisher: 'Team Cherry',
      price: '14.99',
      releaseDate: '2017-02-24',
    },
    {
      title: 'Sekiro Shadows Die Twice',
      genre: 'Action',
      description: 'Carve your path to vengeance in Sengoku Japan.',
      developer: 'FromSoftware',
      publisher: 'Activision',
      price: '59.99',
      releaseDate: '2019-03-22',
    },
    {
      title: 'Doom Eternal',
      genre: 'FPS',
      description: 'Rip and tear through demon hordes.',
      developer: 'id Software',
      publisher: 'Bethesda Softworks',
      price: '39.99',
      releaseDate: '2020-03-20',
    },
    {
      title: 'The Last of Us Part I',
      genre: 'Action',
      description: 'A masterpiece of storytelling and survival.',
      developer: 'Naughty Dog',
      publisher: 'Sony Interactive',
      price: '59.99',
      releaseDate: '2023-03-28',
    },
    {
      title: 'Death Stranding',
      genre: 'Action',
      description: 'A unique open world experience by Kojima.',
      developer: 'Kojima Productions',
      publisher: 'Sony Interactive',
      price: '39.99',
      releaseDate: '2019-11-08',
    },
    {
      title: 'Control',
      genre: 'Action',
      description: 'A supernatural third-person action adventure.',
      developer: 'Remedy Entertainment',
      publisher: '505 Games',
      price: '29.99',
      releaseDate: '2019-08-27',
    },
    {
      title: 'Alan Wake 2',
      genre: 'Horror',
      description: 'A survival horror sequel from Remedy.',
      developer: 'Remedy Entertainment',
      publisher: 'Epic Games Publishing',
      price: '59.99',
      releaseDate: '2023-10-27',
    },
    {
      title: 'Lies of P',
      genre: 'Action RPG',
      description: 'A dark retelling of Pinocchio.',
      developer: 'Round8 Studio',
      publisher: 'Neowiz Games',
      price: '59.99',
      releaseDate: '2023-09-19',
    },
    {
      title: 'Armored Core VI',
      genre: 'Action',
      description: 'Pilot mechs in intense combat.',
      developer: 'FromSoftware',
      publisher: 'Bandai Namco',
      price: '59.99',
      releaseDate: '2023-08-25',
    },
    {
      title: 'Street Fighter 6',
      genre: 'Fighting',
      description: 'The next evolution in fighting games.',
      developer: 'Capcom',
      publisher: 'Capcom',
      price: '59.99',
      releaseDate: '2023-06-02',
    },
    {
      title: 'Mortal Kombat 1',
      genre: 'Fighting',
      description: 'A new era of Mortal Kombat begins.',
      developer: 'NetherRealm Studios',
      publisher: 'Warner Bros. Games',
      price: '69.99',
      releaseDate: '2023-09-19',
    },
    {
      title: 'Tekken 8',
      genre: 'Fighting',
      description: 'The King of Iron Fist Tournament returns.',
      developer: 'Bandai Namco',
      publisher: 'Bandai Namco',
      price: '69.99',
      releaseDate: '2024-01-26',
    },
    {
      title: 'Guilty Gear Strive',
      genre: 'Fighting',
      description: 'A revolutionary anime fighting game.',
      developer: 'Arc System Works',
      publisher: 'Arc System Works',
      price: '39.99',
      releaseDate: '2021-06-11',
    },
    {
      title: 'Dragon Ball FighterZ',
      genre: 'Fighting',
      description: 'A 2D fighter featuring Dragon Ball characters.',
      developer: 'Arc System Works',
      publisher: 'Bandai Namco',
      price: '24.99',
      releaseDate: '2018-01-26',
    },
    {
      title: 'Persona 5 Royal',
      genre: 'RPG',
      description: 'Steal hearts and change the world.',
      developer: 'Atlus',
      publisher: 'Sega',
      price: '59.99',
      releaseDate: '2022-10-21',
    },
    {
      title: 'Persona 4 Golden',
      genre: 'RPG',
      description: 'Solve a mystery in rural Japan.',
      developer: 'Atlus',
      publisher: 'Sega',
      price: '19.99',
      releaseDate: '2020-06-13',
    },
    {
      title: 'Persona 3 Reload',
      genre: 'RPG',
      description: 'Experience the Dark Hour reborn.',
      developer: 'Atlus',
      publisher: 'Sega',
      price: '69.99',
      releaseDate: '2024-02-02',
    },
    {
      title: 'Metaphor ReFantazio',
      genre: 'RPG',
      description: 'A new fantasy RPG from Atlus.',
      developer: 'Atlus',
      publisher: 'Sega',
      price: '69.99',
      releaseDate: '2024-10-11',
    },
    {
      title: 'Final Fantasy VII Rebirth',
      genre: 'RPG',
      description: 'Continue Clouds journey beyond Midgar.',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      price: '69.99',
      releaseDate: '2024-02-29',
    },
    {
      title: 'Final Fantasy XIV',
      genre: 'MMORPG',
      description: 'An award-winning MMORPG experience.',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      price: '39.99',
      releaseDate: '2013-08-27',
    },
    {
      title: 'Dragon Quest XI',
      genre: 'RPG',
      description: 'A classic JRPG adventure.',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      price: '39.99',
      releaseDate: '2018-09-04',
    },
    {
      title: 'Octopath Traveler II',
      genre: 'RPG',
      description: 'Eight travelers, eight stories.',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      price: '59.99',
      releaseDate: '2023-02-24',
    },
    {
      title: 'Triangle Strategy',
      genre: 'Strategy',
      description: 'A tactical RPG with branching narratives.',
      developer: 'Square Enix',
      publisher: 'Square Enix',
      price: '59.99',
      releaseDate: '2022-03-04',
    },
    {
      title: 'Fire Emblem Engage',
      genre: 'Strategy',
      description: 'Summon heroes from across Fire Emblem history.',
      developer: 'Intelligent Systems',
      publisher: 'Nintendo',
      price: '59.99',
      releaseDate: '2023-01-20',
    },
    {
      title: 'Fire Emblem Three Houses',
      genre: 'Strategy',
      description: 'Lead students in tactical combat.',
      developer: 'Intelligent Systems',
      publisher: 'Nintendo',
      price: '59.99',
      releaseDate: '2019-07-26',
    },
    {
      title: 'XCOM 2',
      genre: 'Strategy',
      description: 'Lead the resistance against alien occupation.',
      developer: 'Firaxis Games',
      publisher: '2K Games',
      price: '29.99',
      releaseDate: '2016-02-05',
    },
    {
      title: 'Civilization VI',
      genre: 'Strategy',
      description: 'Build an empire to stand the test of time.',
      developer: 'Firaxis Games',
      publisher: '2K Games',
      price: '29.99',
      releaseDate: '2016-10-21',
    },
    {
      title: 'Total War Warhammer III',
      genre: 'Strategy',
      description: 'Command legendary armies in epic battles.',
      developer: 'Creative Assembly',
      publisher: 'Sega',
      price: '59.99',
      releaseDate: '2022-02-17',
    },
    {
      title: 'Age of Empires IV',
      genre: 'Strategy',
      description: 'Return to history in this RTS classic.',
      developer: 'Relic Entertainment',
      publisher: 'Xbox Game Studios',
      price: '59.99',
      releaseDate: '2021-10-28',
    },
    {
      title: 'Crusader Kings III',
      genre: 'Strategy',
      description: 'Create your own medieval dynasty.',
      developer: 'Paradox Development',
      publisher: 'Paradox Interactive',
      price: '49.99',
      releaseDate: '2020-09-01',
    },
    {
      title: 'Europa Universalis IV',
      genre: 'Strategy',
      description: 'Rule a nation through the ages.',
      developer: 'Paradox Development',
      publisher: 'Paradox Interactive',
      price: '39.99',
      releaseDate: '2013-08-13',
    },
    {
      title: 'Stellaris',
      genre: 'Strategy',
      description: 'Explore the galaxy and build your empire.',
      developer: 'Paradox Development',
      publisher: 'Paradox Interactive',
      price: '39.99',
      releaseDate: '2016-05-09',
    },
    {
      title: 'Cities Skylines II',
      genre: 'Simulation',
      description: 'Build the city of your dreams.',
      developer: 'Colossal Order',
      publisher: 'Paradox Interactive',
      price: '49.99',
      releaseDate: '2023-10-24',
    },
    {
      title: 'Planet Coaster 2',
      genre: 'Simulation',
      description: 'Create the theme park of your dreams.',
      developer: 'Frontier Developments',
      publisher: 'Frontier Developments',
      price: '49.99',
      releaseDate: '2024-11-06',
    },
    {
      title: 'Two Point Hospital',
      genre: 'Simulation',
      description: 'Build and manage wacky hospitals.',
      developer: 'Two Point Studios',
      publisher: 'Sega',
      price: '34.99',
      releaseDate: '2018-08-30',
    },
    {
      title: 'Stardew Valley',
      genre: 'Simulation',
      description: 'Build the farm of your dreams.',
      developer: 'ConcernedApe',
      publisher: 'ConcernedApe',
      price: '14.99',
      releaseDate: '2016-02-26',
    },
    {
      title: 'Terraria',
      genre: 'Sandbox',
      description: 'Dig, fight, explore and build.',
      developer: 'Re-Logic',
      publisher: 'Re-Logic',
      price: '9.99',
      releaseDate: '2011-05-16',
    },
    {
      title: 'Minecraft',
      genre: 'Sandbox',
      description: 'Create and explore blocky worlds.',
      developer: 'Mojang Studios',
      publisher: 'Xbox Game Studios',
      price: '26.99',
      releaseDate: '2011-11-18',
    },
    {
      title: 'Valheim',
      genre: 'Survival',
      description: 'A Viking survival experience.',
      developer: 'Iron Gate AB',
      publisher: 'Coffee Stain Publishing',
      price: '19.99',
      releaseDate: '2021-02-02',
    },
    {
      title: 'Subnautica',
      genre: 'Survival',
      description: 'Survive an alien underwater world.',
      developer: 'Unknown Worlds',
      publisher: 'Unknown Worlds',
      price: '29.99',
      releaseDate: '2018-01-23',
    },
    {
      title: 'The Forest',
      genre: 'Survival',
      description: 'Survive in a mysterious forest.',
      developer: 'Endnight Games',
      publisher: 'Endnight Games',
      price: '19.99',
      releaseDate: '2018-04-30',
    },
    {
      title: 'Sons of the Forest',
      genre: 'Survival',
      description: 'Survive on a cannibal-infested island.',
      developer: 'Endnight Games',
      publisher: 'Newnight',
      price: '29.99',
      releaseDate: '2023-02-23',
    },
    {
      title: 'Rust',
      genre: 'Survival',
      description: 'Survive in a harsh open world.',
      developer: 'Facepunch Studios',
      publisher: 'Facepunch Studios',
      price: '39.99',
      releaseDate: '2018-02-08',
    },
    {
      title: 'ARK Survival Evolved',
      genre: 'Survival',
      description: 'Tame dinosaurs and survive.',
      developer: 'Studio Wildcard',
      publisher: 'Studio Wildcard',
      price: '29.99',
      releaseDate: '2017-08-29',
    },
    {
      title: 'No Mans Sky',
      genre: 'Exploration',
      description: 'Explore an infinite procedural universe.',
      developer: 'Hello Games',
      publisher: 'Hello Games',
      price: '59.99',
      releaseDate: '2016-08-09',
    },
    {
      title: 'Elite Dangerous',
      genre: 'Simulation',
      description: 'Command your ship in a realistic galaxy.',
      developer: 'Frontier Developments',
      publisher: 'Frontier Developments',
      price: '29.99',
      releaseDate: '2014-12-16',
    },
    {
      title: 'Star Citizen',
      genre: 'Simulation',
      description: 'The ultimate space simulation.',
      developer: 'Cloud Imperium Games',
      publisher: 'Cloud Imperium Games',
      price: '45.00',
      releaseDate: '2024-12-01',
    },
    {
      title: 'Outer Wilds',
      genre: 'Exploration',
      description: 'Explore a solar system stuck in a time loop.',
      developer: 'Mobius Digital',
      publisher: 'Annapurna Interactive',
      price: '24.99',
      releaseDate: '2019-05-28',
    },
    {
      title: 'Disco Elysium',
      genre: 'RPG',
      description: 'A groundbreaking detective RPG.',
      developer: 'ZA/UM',
      publisher: 'ZA/UM',
      price: '39.99',
      releaseDate: '2019-10-15',
    },
    {
      title: 'Divinity Original Sin 2',
      genre: 'RPG',
      description: 'A deep tactical RPG experience.',
      developer: 'Larian Studios',
      publisher: 'Larian Studios',
      price: '44.99',
      releaseDate: '2017-09-14',
    },
    {
      title: 'Pillars of Eternity II',
      genre: 'RPG',
      description: 'An epic voyage of discovery.',
      developer: 'Obsidian Entertainment',
      publisher: 'Versus Evil',
      price: '39.99',
      releaseDate: '2018-05-08',
    },
    {
      title: 'Pathfinder Wrath of the Righteous',
      genre: 'RPG',
      description: 'Lead a crusade against demon hordes.',
      developer: 'Owlcat Games',
      publisher: 'META Publishing',
      price: '49.99',
      releaseDate: '2021-09-02',
    },
    {
      title: 'Wasteland 3',
      genre: 'RPG',
      description: 'A post-apocalyptic tactical RPG.',
      developer: 'inXile Entertainment',
      publisher: 'Deep Silver',
      price: '39.99',
      releaseDate: '2020-08-28',
    },
    {
      title: 'Fallout 4',
      genre: 'RPG',
      description: 'Explore the post-nuclear Commonwealth.',
      developer: 'Bethesda Game Studios',
      publisher: 'Bethesda Softworks',
      price: '19.99',
      releaseDate: '2015-11-10',
    },
    {
      title: 'Fallout New Vegas',
      genre: 'RPG',
      description: 'Adventure in the Mojave Wasteland.',
      developer: 'Obsidian Entertainment',
      publisher: 'Bethesda Softworks',
      price: '9.99',
      releaseDate: '2010-10-19',
    },
    {
      title: 'The Elder Scrolls V Skyrim',
      genre: 'RPG',
      description: 'Become the Dragonborn.',
      developer: 'Bethesda Game Studios',
      publisher: 'Bethesda Softworks',
      price: '39.99',
      releaseDate: '2011-11-11',
    },
    {
      title: 'Mass Effect Legendary Edition',
      genre: 'RPG',
      description: 'The complete Mass Effect trilogy.',
      developer: 'BioWare',
      publisher: 'Electronic Arts',
      price: '59.99',
      releaseDate: '2021-05-14',
    },
    {
      title: 'Dragon Age Inquisition',
      genre: 'RPG',
      description: 'Lead the Inquisition against darkness.',
      developer: 'BioWare',
      publisher: 'Electronic Arts',
      price: '29.99',
      releaseDate: '2014-11-18',
    },
    {
      title: 'Dragon Age The Veilguard',
      genre: 'RPG',
      description: 'Stop the elven gods from destroying the world.',
      developer: 'BioWare',
      publisher: 'Electronic Arts',
      price: '69.99',
      releaseDate: '2024-10-31',
    },
    {
      title: 'Borderlands 3',
      genre: 'FPS',
      description: 'Shoot and loot across the galaxy.',
      developer: 'Gearbox Software',
      publisher: '2K Games',
      price: '29.99',
      releaseDate: '2019-09-13',
    },
    {
      title: 'Tiny Tinas Wonderlands',
      genre: 'FPS',
      description: 'A fantasy looter shooter adventure.',
      developer: 'Gearbox Software',
      publisher: '2K Games',
      price: '59.99',
      releaseDate: '2022-03-25',
    },
    {
      title: 'Destiny 2',
      genre: 'FPS',
      description: 'A free-to-play online shooter.',
      developer: 'Bungie',
      publisher: 'Bungie',
      price: '0.00',
      releaseDate: '2017-10-24',
    },
    {
      title: 'Warframe',
      genre: 'Action',
      description: 'A free-to-play sci-fi action game.',
      developer: 'Digital Extremes',
      publisher: 'Digital Extremes',
      price: '0.00',
      releaseDate: '2013-03-25',
    },
    {
      title: 'Path of Exile',
      genre: 'Action RPG',
      description: 'A free-to-play dark fantasy ARPG.',
      developer: 'Grinding Gear Games',
      publisher: 'Grinding Gear Games',
      price: '0.00',
      releaseDate: '2013-10-23',
    },
    {
      title: 'Path of Exile 2',
      genre: 'Action RPG',
      description: 'The sequel to the legendary ARPG.',
      developer: 'Grinding Gear Games',
      publisher: 'Grinding Gear Games',
      price: '0.00',
      releaseDate: '2024-12-06',
    },
    {
      title: 'Lost Ark',
      genre: 'MMORPG',
      description: 'An action-packed MMORPG adventure.',
      developer: 'Smilegate RPG',
      publisher: 'Amazon Games',
      price: '0.00',
      releaseDate: '2022-02-11',
    },
    {
      title: 'Guild Wars 2',
      genre: 'MMORPG',
      description: 'A living world MMORPG.',
      developer: 'ArenaNet',
      publisher: 'NCSOFT',
      price: '0.00',
      releaseDate: '2012-08-28',
    },
    {
      title: 'Black Desert Online',
      genre: 'MMORPG',
      description: 'An action MMORPG with deep systems.',
      developer: 'Pearl Abyss',
      publisher: 'Pearl Abyss',
      price: '9.99',
      releaseDate: '2016-03-03',
    },
    {
      title: 'The Crew Motorfest',
      genre: 'Racing',
      description: 'An open-world racing festival.',
      developer: 'Ubisoft Ivory Tower',
      publisher: 'Ubisoft',
      price: '69.99',
      releaseDate: '2023-09-14',
    },
    {
      title: 'Gran Turismo 7',
      genre: 'Racing',
      description: 'The real driving simulator.',
      developer: 'Polyphony Digital',
      publisher: 'Sony Interactive',
      price: '69.99',
      releaseDate: '2022-03-04',
    },
    {
      title: 'F1 24',
      genre: 'Racing',
      description: 'The official Formula 1 game.',
      developer: 'Codemasters',
      publisher: 'Electronic Arts',
      price: '69.99',
      releaseDate: '2024-05-31',
    },
    {
      title: 'Dirt Rally 2.0',
      genre: 'Racing',
      description: 'Master the art of rally racing.',
      developer: 'Codemasters',
      publisher: 'Codemasters',
      price: '24.99',
      releaseDate: '2019-02-26',
    },
    {
      title: 'Assetto Corsa Competizione',
      genre: 'Racing',
      description: 'The official GT World Challenge game.',
      developer: 'Kunos Simulazioni',
      publisher: '505 Games',
      price: '39.99',
      releaseDate: '2019-05-29',
    },
    {
      title: 'Rainbow Six Siege',
      genre: 'FPS',
      description: 'A tactical team-based shooter.',
      developer: 'Ubisoft Montreal',
      publisher: 'Ubisoft',
      price: '19.99',
      releaseDate: '2015-12-01',
    },
    {
      title: 'Counter-Strike 2',
      genre: 'FPS',
      description: 'The next evolution of Counter-Strike.',
      developer: 'Valve',
      publisher: 'Valve',
      price: '0.00',
      releaseDate: '2023-09-27',
    },
    {
      title: 'Valorant',
      genre: 'FPS',
      description: 'A tactical hero shooter from Riot Games.',
      developer: 'Riot Games',
      publisher: 'Riot Games',
      price: '0.00',
      releaseDate: '2020-06-02',
    },
    {
      title: 'Overwatch 2',
      genre: 'FPS',
      description: 'A team-based hero shooter.',
      developer: 'Blizzard Entertainment',
      publisher: 'Blizzard Entertainment',
      price: '0.00',
      releaseDate: '2022-10-04',
    },
    {
      title: 'Apex Legends',
      genre: 'Battle Royale',
      description: 'A free-to-play battle royale hero shooter.',
      developer: 'Respawn Entertainment',
      publisher: 'Electronic Arts',
      price: '0.00',
      releaseDate: '2019-02-04',
    },
    {
      title: 'Fortnite',
      genre: 'Battle Royale',
      description: 'Build, battle, and be the last one standing.',
      developer: 'Epic Games',
      publisher: 'Epic Games',
      price: '0.00',
      releaseDate: '2017-07-21',
    },
    {
      title: 'PUBG Battlegrounds',
      genre: 'Battle Royale',
      description: 'The original battle royale experience.',
      developer: 'PUBG Studios',
      publisher: 'Krafton',
      price: '0.00',
      releaseDate: '2017-12-20',
    },
    {
      title: 'Hunt Showdown',
      genre: 'FPS',
      description: 'A competitive first-person bounty hunting game.',
      developer: 'Crytek',
      publisher: 'Crytek',
      price: '39.99',
      releaseDate: '2019-08-27',
    },
    {
      title: 'Escape from Tarkov',
      genre: 'FPS',
      description: 'A hardcore realistic online shooter.',
      developer: 'Battlestate Games',
      publisher: 'Battlestate Games',
      price: '44.99',
      releaseDate: '2017-07-27',
    },
    {
      title: 'DayZ',
      genre: 'Survival',
      description: 'Survive the zombie apocalypse.',
      developer: 'Bohemia Interactive',
      publisher: 'Bohemia Interactive',
      price: '44.99',
      releaseDate: '2018-12-13',
    },
    {
      title: 'Project Zomboid',
      genre: 'Survival',
      description: 'An isometric zombie survival game.',
      developer: 'The Indie Stone',
      publisher: 'The Indie Stone',
      price: '19.99',
      releaseDate: '2013-11-08',
    },
    {
      title: 'Left 4 Dead 2',
      genre: 'FPS',
      description: 'Cooperative zombie shooting action.',
      developer: 'Valve',
      publisher: 'Valve',
      price: '9.99',
      releaseDate: '2009-11-17',
    },
    {
      title: 'Back 4 Blood',
      genre: 'FPS',
      description: 'A thrilling cooperative shooter.',
      developer: 'Turtle Rock Studios',
      publisher: 'Warner Bros. Games',
      price: '59.99',
      releaseDate: '2021-10-12',
    },
    {
      title: 'Deep Rock Galactic',
      genre: 'FPS',
      description: 'Co-op mining and shooting in space.',
      developer: 'Ghost Ship Games',
      publisher: 'Coffee Stain Publishing',
      price: '29.99',
      releaseDate: '2020-05-13',
    },
    {
      title: 'Phasmophobia',
      genre: 'Horror',
      description: 'Cooperative ghost hunting.',
      developer: 'Kinetic Games',
      publisher: 'Kinetic Games',
      price: '13.99',
      releaseDate: '2020-09-18',
    },
    {
      title: 'Lethal Company',
      genre: 'Horror',
      description: 'Collect scrap on abandoned moons.',
      developer: 'Zeekerss',
      publisher: 'Zeekerss',
      price: '9.99',
      releaseDate: '2023-10-23',
    },
    {
      title: 'Content Warning',
      genre: 'Horror',
      description: 'Film spooky content for views.',
      developer: 'Landfall',
      publisher: 'Landfall',
      price: '7.99',
      releaseDate: '2024-04-01',
    },
    {
      title: 'It Takes Two',
      genre: 'Adventure',
      description: 'A co-op adventure about mending relationships.',
      developer: 'Hazelight Studios',
      publisher: 'Electronic Arts',
      price: '39.99',
      releaseDate: '2021-03-26',
    },
    {
      title: 'A Way Out',
      genre: 'Adventure',
      description: 'A co-op prison escape adventure.',
      developer: 'Hazelight Studios',
      publisher: 'Electronic Arts',
      price: '29.99',
      releaseDate: '2018-03-23',
    },
    {
      title: 'Cuphead',
      genre: 'Action',
      description: 'A run and gun game with 1930s animation style.',
      developer: 'Studio MDHR',
      publisher: 'Studio MDHR',
      price: '19.99',
      releaseDate: '2017-09-29',
    },
    {
      title: 'Celeste',
      genre: 'Platformer',
      description: 'Help Madeline climb Celeste Mountain.',
      developer: 'Maddy Makes Games',
      publisher: 'Maddy Makes Games',
      price: '19.99',
      releaseDate: '2018-01-25',
    },
    {
      title: 'Dead Cells',
      genre: 'Roguelike',
      description: 'A roguevania action platformer.',
      developer: 'Motion Twin',
      publisher: 'Motion Twin',
      price: '24.99',
      releaseDate: '2018-08-07',
    },
    {
      title: 'Slay the Spire',
      genre: 'Roguelike',
      description: 'A deck-building roguelike adventure.',
      developer: 'Mega Crit Games',
      publisher: 'Mega Crit Games',
      price: '24.99',
      releaseDate: '2019-01-23',
    },
    {
      title: 'Vampire Survivors',
      genre: 'Roguelike',
      description: 'A gothic horror survival game.',
      developer: 'poncle',
      publisher: 'poncle',
      price: '4.99',
      releaseDate: '2022-10-20',
    },
  ];

  for (let i = 0; i < games.length; i++) {
    const gameData = games[i];
    const game = await prisma.game.create({
      data: {
        keys: [
          `KEY-${i + 1}-001`,
          `KEY-${i + 1}-002`,
          `KEY-${i + 1}-003`,
          `KEY-${i + 1}-004`,
          `KEY-${i + 1}-005`,
        ],
        quantity: 5,
        title: gameData.title,
        genre: gameData.genre,
        buyCount: Math.floor(Math.random() * 1000),
        description: gameData.description,
        trailer: `https://www.youtube.com/watch?v=example${i + 1}`,
        primaryImage: `/uploads/games/${gameData.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}.jpg`,
        additionalImages: [
          `/uploads/games/${gameData.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-1.jpg`,
          `/uploads/games/${gameData.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-2.jpg`,
        ],
        logo: `/uploads/logos/${gameData.title.toLowerCase().replace(/[^a-z0-9]/g, '-')}-logo.png`,
        price: gameData.price,
        developer: gameData.developer,
        publisher: gameData.publisher,
        releaseDate: gameData.releaseDate,
        platforms: ['Windows', 'PlayStation 5', 'Xbox Series X'],
        minOS: 'Windows 10 64-bit',
        minCPU: 'Intel Core i5-4460 / AMD Ryzen 3 1200',
        minMemory: '8 GB RAM',
        minGPU: 'NVIDIA GTX 960 / AMD Radeon RX 470',
        minStorage: '50 GB',
        recOS: 'Windows 10/11 64-bit',
        recCPU: 'Intel Core i7-8700 / AMD Ryzen 5 3600',
        recMemory: '16 GB RAM',
        recGPU: 'NVIDIA RTX 2060 / AMD Radeon RX 5700 XT',
        recStorage: '100 GB SSD',
      },
    });
    console.log(`Created game ${i + 1}/123: ${game.title}`);
  }

  console.log(`\nSeeding completed! Total games: ${games.length}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
